language: python
os: linux
dist: bionic
python:
   - "3.6"
   - "3.7"
   - "3.8"
env:
   - TESTDB=sqlite
   - TESTDB=postgres
   - TESTDB=mysql

services:
   - postgresql
   - mysql

addons:
  apt:
    packages:
      - gir1.2-gtk-3.0
      - python3-gi
      - librsvg2-common
      - libgirepository1.0-dev
      - pkg-config
      - libcairo2-dev

cache:
  directories:
    - $HOME/.cache/pip

# We need to set the collation order on the postgres database to match the other dbs,
# This requires using template0, since this differs from the locale settings for the
# standard template.
before_install:
   - if [ "$TESTDB" = "postgres" ]; then pip install psycopg2 ; fi
   - if [ "$TESTDB" = "mysql" ]; then pip install mysql-connector ; fi
   - mysql -uroot -e 'drop database sutekh_test;' ; mysql -uroot -e 'create database sutekh_test;'
   - dropdb -U postgres -w sutekh_test ; createdb -U postgres --lc-collate=C.UTF-8 --template template0 -w sutekh_test

install:
   - pip install mock pytest keyring ply sqlobject configobj PyGObject pycairo
# command to run tests
script: ci/travis/run_travis_tests.sh
